server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instanceId: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 后还可加上路由路径前缀
  routes:
    items-service: /item/** #路由到商品的微服务
